version: '3'
services:
  db:
    image: mongo:4.4.14
    container_name: pollitdb 
    volumes:
      - ./data/mongodb/db:/data/db:z
    ports:
    - "4000:27017"
    restart: always
  pollitAdmin_backend:
    image: pollitadmin_backend
    build: 
      context: ./pollit-admin-backend
      dockerfile: Dockerfile-dev
    container_name: pollitadmin_backend
    volumes:
      - /tmp/pollit-admin-backend/npm-cache:/root/.npm:z
      - ./pollit-admin-backend/src:/usr/src/app/src:z
    ports:
     - "1235:1235"
    environment: 
     - PORT=1235
     - NODE_ENV=development
     - DBHOST=mongodb://pollitdb:27017
     - RABBIT=amqp://guest:guest@rabbit:5672
     - ACCOUNTS_MICROS=http://accounts_micros:1238
     - BLOGS_MICROS=http://blogs_micros:1241
     - DEMOGRAPHY_MICROS=http://demography_micros:1239 
     - POLLS_MICROS=http://polls_micros:1240
     - DBNAME=pollit
     - JWKSURI=https://dev-xu6xg5to.us.auth0.com/.well-known/jwks.json
     - AUDIENCE=https://pollitAdmin25804-backend
     - ISSUER=https://auth.pollitng.com/
     - CORSORIGIN=http://localhost:1234
     - POLLIT_REPORTING=http://pollit-reporting:4002
     - FILE_STORAGE_HOST=fileshare-micros
     - FILE_STORAGE_PORT=80
    restart: "no"
  pollitAdmin_frontend:
    image:  pollitadmin_frontend
    build:
      context: ./pollit-admin-frontend
      dockerfile: Dockerfile-dev
    container_name: pollitadmin_frontend 
    volumes:
      - /tmp/pollit-admin-frontend/npm-cache:/root/.npm:z
      - ./pollitadmin_frontend_app/dist:/usr/src/app/dist:z
      - ./pollit-admin-frontend/server.js:/usr/src/app/server.js:z
    ports:
      - "1234:1234"
    environment:
      - PORT=1234
      - NODE_ENV=production
      - ServerURL=http://pollitadmin_backend:1235
    restart: "no"
  pollit_backend:
    image: pollit_backend
    build:
      context: ./pollit-backend
      dockerfile: Dockerfile-dev
    container_name: pollit_backend
    volumes:
      - /tmp/pollit-backend/npm-cache:/root/.npm:z
      - ./pollit-backend/src:/usr/src/app/src:z
    ports:
      - "1237:1237"
    environment:
      - "PORT=1237"
      - NODE_ENV=development
      - DBHOST=mongodb://pollitdb:27017
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBNAME=pollit
      - AWS_ACCESS_KEY_ID=AKIAT37BHWD3GKQORZOI
      - AWS_SECRET_ACCESS_KEY=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
      - ACCOUNTS_MICROS=http://accounts_micros:1238
      - DEMOGRAPHY_MICROS=http://demography_micros:1239 
      - POLLS_MICROS=http://polls_micros:1240
      - BLOGS_MICROS=http://blogs_micros:1241
      - JWKSURI=https://dev-xu6xg5to.us.auth0.com/.well-known/jwks.json
      - AUDIENCE=https://pollit62339-backend
      - ISSUER=https://auth.pollitng.com/
      - POLLIT_REPORTING=http://pollit-reporting:4002
      - CORSORIGIN=http://localhost:1236
      - FILE_STORAGE_HOST=fileshare-micros
      - FILE_STORAGE_PORT=80
    restart:  "no"
  pollit_frontend:
    image:  pollit_frontend
    build:  
      context: ./pollit-frontend
      dockerfile: Dockerfile-dev
    container_name: pollit_frontend
    volumes:
      - /tmp/pollit-frontend/npm-cache:/root/.npm:z
      - ./pollit_frontend_app/dist:/usr/src/app/dist:z
      - ./pollit-frontend/server.js:/usr/src/app/server.js:z
    ports:
      - "1236:1236"
    environment:
      - PORT=1236
      - NODE_ENV=production
      - ServerURL=http://pollit_backend:1237
    restart:  "no"
  pollitreporting:
    image: pollitreporting
    build:
      context: ./pollit-reporting
      dockerfile: Dockerfile-dev 
    container_name: pollit-reporting
    volumes:
      - /tmp/pollit-reporting/npm-cache:/root/.npm:z
      - ./pollit-reporting/src:/usr/src/app/src:z
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DB=mongodb://pollitdb:27017
      - DBNAME=pollitreporting
      - NODE_ENV=development
    depends_on:
      - db
      - rabbit
    restart: "no"
  rabbit:
    image: rabbitmq:3.8.1-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart:  always
  accounts_micros:
    image: accounts_micros
    build:
      context: ./accounts-micros
      dockerfile: Dockerfile-dev
    container_name: accounts-micros
    volumes:
      - /tmp/accounts-micros/npm-cache:/root/.npm:z
      - ./accounts-micros/src:/usr/src/app/src:z
    ports:
      - "1238:1238"
    environment:
      - "PORT=1238"
      - NODE_ENV=development
      - DB=mongodb://pollitdb:27017/accounts
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DEMOGRAPHY_MICROS=http://accounts_micros:1239 
      - POLLS_MICROS=http://polls_micros:1240
      - POLLIT_REPORTING=http://pollit-reporting:4002
    restart:  "no"
  demography_micros:
    image: demography_micros
    build:
      context: ./demography-micros
      dockerfile: Dockerfile-dev
    container_name: demography_micros
    volumes:
      - /tmp/demography-micros/npm-cache:/root/.npm:z
      - ./demography-micros/src:/usr/src/app/src:z
    ports:
      - "1239:1239"
    environment:
      - "PORT=1239"
      - NODE_ENV=development
      - DB=mongodb://pollitdb:27017/demography
      - RABBIT=amqp://guest:guest@rabbit:5672
      - ACCOUNTS_MICROS=http://accounts_micros:1238
      - POLLS_MICROS=http://polls_micros:1240
      - POLLIT_REPORTING=http://pollit-reporting:4002
    restart:  "no"
  polls_micros:
    image: polls_micros
    build:
      context: ./polls-micros
      dockerfile: Dockerfile-dev
    container_name: polls_micros
    volumes:
      - /tmp/polls-micros/npm-cache:/root/.npm:z
      - ./polls-micros/src:/usr/src/app/src:z
    ports:
      - "1240:1240"
    environment:
      - PORT=1240
      - NODE_ENV=development
      - DB=mongodb://pollitdb:27017/polls
      - RABBIT=amqp://guest:guest@rabbit:5672
      - ACCOUNTS_MICROS=http://accounts_micros:1238
      - DEMOGRAPHY_MICROS=http://demography_micros:1239
      - POLLIT_REPORTING=http://pollit-reporting:4002
    restart:  "no"
  blogs_micros:
    image: blogs_micros
    build:
      context: ./blogs-micros
      dockerfile: Dockerfile-dev
    container_name: blogs_micros
    volumes:
      - /tmp/blogs-micros/npm-cache:/root/.npm:z
      - ./blogs-micros/src:/usr/src/app/src:z
    ports:
      - "1241:1241"
    environment:
      - PORT=1241
      - NODE_ENV=development
      - DB=mongodb://pollitdb:27017/blogs 
      - RABBIT=amqp://guest:guest@rabbit:5672
    restart: "no"

