version: '3'
services:
  db:
    image: mongo:4.4.14
    container_name: pollitdb 
    ports:
    - "4000:27017"
    restart: always
  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: Dockerfile-dev
    container_name: fileshare-micros
    volumes:
      - /tmp/azure-storage/npm-cache:/root/.npm:z
      - ./azure-storage/src:/usr/src/app/src:z
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - NODE_ENV=development
      - STORAGE_ACCOUNT_NAME=pollitstore
      - STORAGE_ACCESS_KEY=yaiq9/3JCZHXUf+xk2Rh9GhCl6M8HgWBzR6Ok2/7+uDtj0CSGiloIeqyzAJhK0s0iY9IPkw9ZAXv+AStYkBNKg==
    restart: "no"
  pollitAdmin_backend:
    image: pollitadmin_backend
    build: 
      context: ./pollitadmin-backend
      dockerfile: Dockerfile-dev
    container_name: pollitadmin_backend
    volumes:
      - /tmp/pollitadmin-backend/npm-cache:/root/.npm:z
      - ./pollitadmin-backend/src:/usr/src/app/src:z
    ports:
     - "1235:1235"
    environment:
     - PORT=1235
     - NODE_ENV=development
     - DBHOST=mongodb://pollitdb:27017
     - RABBIT=amqp://guest:guest@rabbit:5672
     - DBNAME=pollit
     - FILE_STORAGE_HOST=fileshare-micros
     - FILE_STORAGE_PORT=80
    restart: "no"
  pollitAdmin_frontend:
    image:  pollitadmin_frontend
    build:
      context: ./pollitadmin-frontend
      dockerfile: Dockerfile-dev
    container_name: pollitadmin_frontend 
    volumes:
      - /tmp/pollitadmin-frontend/npm-cache:/root/.npm:z
      - ./pollitadmin-frontend/src:/usr/src/app/src:z
      - ./pollitadmin_frontend_app/dist:/usr/src/app/dist:z
      - ./pollitadmin-frontend/server.js:/usr/src/app/server.js:z
    ports:
      - "1234:1234"
    environment:
      - PORT=1234
      - OKTADOMAIN=dev-xu6xg5to.us.auth0.com
      - RABBIT=amqp://guest:guest@rabbit:5672
      - CLIENTID=Ox7dS34fE2paZ1nLwVfMNt9bnenBVfSN
      - NODE_ENV=production
      - DBHOST=mongodb://pollitdb:27017
      - DBNAME=pollit
      - ServerURL=http://pollitadmin_backend:1235
    restart: "no"
  pollit_backend:
    image: pollit_backend
    build:
      context: ./pollit-backend
      dockerfile: Dockerfile-dev
    container_name: pollit_backend
    volumes:
      - /tmp/pollit-backend/npm-cache:/root/.npm:z
      - ./pollit-backend/src:/usr/src/app/src:z
    ports:
      - "1237:1237"
    environment:
      - "PORT=1237"
      - NODE_ENV=development
      - DBHOST=mongodb://pollitdb:27017
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBNAME=pollit
      - FILE_STORAGE_HOST=fileshare-micros
      - FILE_STORAGE_PORT=80
    restart:  "no"
  pollit_frontend:
    image:  pollit_frontend
    build:  
      context: ./pollit-frontend
      dockerfile: Dockerfile-dev
    container_name: pollit_frontend
    volumes:
      - /tmp/pollit-frontend/npm-cache:/root/.npm:z
      - ./pollit-frontend/src:/usr/src/app/src:z
      - ./pollit_frontend_app/dist:/usr/src/app/dist:z
      - ./pollit-frontend/server.js:/usr/src/app/server.js:z
    ports:
      - "1236:1236"
    environment:
      - PORT=1236
      - OKTADOMAIN=dev-xu6xg5to.us.auth0.com
      - CLIENTID=54dMmNmxhBYuHOn9I3kio5QialsQQO9f
      - RABBIT=amqp://guest:guest@rabbit:5672
      - NODE_ENV=production
      - DBHOST=mongodb://pollitdb:27017
      - DBNAME=pollit
      - ServerURL=http://pollit_backend:1237
    restart:  "no"
  pollitreporting:
    image: pollitreporting
    build:
      context: ./pollitreporting
      dockerfile: Dockerfile-dev 
    container_name: pollitreporting
    volumes:
      - /tmp/pollitreporting/npm-cache:/root/.npm:z
      - ./pollitreporting/src:/usr/src/app/src:z
    ports:
      - "4002:80"
    environment:
      - PORT=80
      - RABBIT=amqp://guest:guest@rabbit:5672
      - DBHOST=mongodb://pollitdb:27017
      - DBNAME=pollitreporting
      - NODE_ENV=development
    depends_on:
      - db
      - rabbit
    restart: "no"
  rabbit:
    image: rabbitmq:3.8.1-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart:  always