FROM node:12.18.1-alpine

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --only=production 
COPY ./server.js ./server.js
COPY ../pollit_frontend_app/dist ./dist
npx wait-port rabbit:5672 &&
CMD npm start